export const LOGIN = "LOGIN";
export const LOGIN_ADMIN = "LOGIN_ADMIN";
export const LOGOUT = "LOGOUT";

export const FETCH_CATEGORY = "FETCH_CATEGORY";

export const FETCH_PRODUCT_NEW_STYLE = "FETCH_PRODUCT_NEW_STYLE";
export const FETCH_PRODUCT_BY_CATEGORY_NAME = "FETCH_PRODUCT_BY_CATEGORY_NAME";

export const FETCH_PRODUCT_DETAIL = "FETCH_PRODUCT_DETAIL";

export const ADD_TO_CART = "ADD_TO_CART";
export const DELETED_FROM_CART = "DELETED_FROM_CART";

export const AMOUNT_PRODUCT = "AMOUNT_PRODUCT";
export const GET_PRODUCT = "GET_PRODUCT";
export const ORDER_DELETE_PRODUCT = "ORDER_DELETE_PRODUCT";

export const ADD_AMOUNT = "ADD_AMOUNT";

export const ADD_TOTAL = "ADD_TOTAL";

export const FETCH_ALL_ORDERS = "FETCH_ALL_ORDERS";